title: "My Multilingual Site"
baseurl: ""
permalink: pretty

languages:
  - code: en
    name: "English"
  - code: fr
    name: "Français"

pages:
  - id: "page1"
    title: "Page 1"
  - id: "page2"
    title: "Page 2"
